[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "SKIP_ENV_VALIDATION=true bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  DISABLE_ESLINT_PLUGIN = "true"

# Temporarily disable Next.js plugin to avoid strict linting
# [[plugins]]
#   package = "@netlify/plugin-nextjs"
